# Training configuration
training:
  # batch_size: 32  # Batch size for training
  batch_size: 2 # Batch size for training
  learning_rate: 0.001
  num_epochs: 1
  # device: "cuda" # Use "cuda" for GPU or "cpu" for CPU
  device: "cpu" # Use "cuda" for GPU or "cpu" for CPU

# Data configuration
data:
  train_file: "data/dailydialog/train/train.csv"
  val_file: "data/MELD/val_utterances.csv"
  test_file: "data/MELD/test_utterances.csv"

# Label mappings
labels:
  # no_emotion: 0,
  # anger: 1,
  # disgust: 2,
  # fear: 3,
  # happiness: 4,
  # sadness: 5,
  # surprise: 6,

  neutral: 0,
  joy: 1,
  # happiness: 1,
  # excited: 1,
  surprise: 2,
  anger: 3,
  # frustration: 3,
  sadness: 4,
  disgust: 5,
  fear: 6,

  # positive: 1
  # negative: -1
  # neutral: 0
